apiVersion: v1
kind: ConfigMap
metadata:
  name: mylinks-config
  labels:
    app.kubernetes.io/name: mylinks
data:
  NODE_ENV: "production"
  PORT: "3000"
  DATA_DIR: "/data"
  DEV_MODE: "false"
  ADMIN_USERS: "arvesv,tailnet-user"
